import { StyleSheet } from "react-native";

export const loginStyle = StyleSheet.create({
    formContainer:{
        flex:1,
        paddingHorizontal:30,
        justifyContent:'center',
        height:600,
        marginBottom:80
    },
    title:{
        color:'white',
        fontSize:30,
        fontWeight:"bold"
    },
    label:{
        marginTop:25,
        color:'white',
        fontWeight:"bold"
    },
    inputField:{
        color:'white',
        fontSize:20
    },
    buttonContainer:{
        alignItems:'center',
        marginTop:50
    },
    button:{
        borderWidth:2,
        borderColor:'white',
        paddingHorizontal:70,
        paddingVertical:5,
        borderRadius:100,
        backgroundColor:'white'
    },
    buttonText:{
        fontSize:18,
        color:'black'
    }
});