// Generated by https://quicktype.io

export interface ResultLogin {
    ok:    boolean;
    msg:   string;
    user:  Usuario;
    token: string;
}

export interface Usuario {
    _id:     string;
    nombre:  string;
    usuario: string;
    rol:     string;
    estado:  boolean;
    img?:    string
}

export interface LoginData {
    usuario:string;
    password:string
}